//
//  PropertyModel.swift
//  Webflow
//
//  Created by Nick Black on 11/8/23.
//

import Foundation
import SwiftUI

struct PropertyModel {
	enum Alignment {
		case normal
		case stretch
		case center
		case start
		case end
	}
	
	let accentColor: Color?
	let alignContent: Alignment?
	let alignItems: Alignment?
	let alignSelf: Alignment?
	let aspectRatio: String?
	let backdropFilter: String?
	let backfaceVisibility: String?
	let background: String?
	let backgroundAttachment: String?
	let backgroundBlendMode: String?
	let backgroundClip: String?
	let backgroundColor: String?
	let backgroundImage: String?
	let backgroundOrigin: String?
	let backgroundPosition: String?
	let backgroundPositionX: String?
	let backgroundPositionY: String?
	let backgroundRepeat: String?
	let backgroundSize: String?
	let blockSize: String?
	let border: String?
	let borderBlock: String?
	let borderBlockColor: String?
	let borderBlockEnd: String?
	let borderBlockEndColor: String?
	let borderBlockEndStyle: String?
	let borderBlockEndWidth: String?
	let borderBlockStart: String?
	let borderBlockStartColor: String?
	let borderBlockStartStyle: String?
	let borderBlockStartWidth: String?
	let borderBlockStyle: String?
	let borderBlockWidth: String?
	let borderBottom: String?
	let borderBottomColor: String?
	let borderBottomLeftRadius: String?
	let borderBottomRightRadius: String?
	let borderBottomStyle: String?
	let borderBottomWidth: String?
	let borderCollapse: String?
	let borderColor: String?
	let borderEndEndRadius: String?
	let borderEndStartRadius: String?
	let borderImage: String?
	let borderImageOutset: String?
	let borderImageRepeat: String?
	let borderImageSlice: String?
	let borderImageSource: String?
	let borderImageWidth: String?
	let borderInline: String?
	let borderInlineColor: String?
	let borderInlineEnd: String?
	let borderInlineEndColor: String?
	let borderInlineEndStyle: String?
	let borderInlineEndWidth: String?
	let borderInlineStart: String?
	let borderInlineStartColor: String?
	let borderInlineStartStyle: String?
	let borderInlineStartWidth: String?
	let borderInlineStyle: String?
	let borderInlineWidth: String?
	let borderLeft: String?
	let borderLeftColor: String?
	let borderLeftStyle: String?
	let borderLeftWidth: String?
	let borderRadius: String?
	let borderRight: String?
	let borderRightColor: String?
	let borderRightStyle: String?
	let borderRightWidth: String?
	let borderSpacing: String?
	let borderStartEndRadius: String?
	let borderStartStartRadius: String?
	let borderStyle: String?
	let borderTop: String?
	let borderTopColor: String?
	let borderTopLeftRadius: String?
	let borderTopRightRadius: String?
	let borderTopStyle: String?
	let borderTopWidth: String?
	let borderWidth: String?
	let bottom: String?
	let boxDecorationBreak: String?
	let boxReflect: String?
	let boxShadow: String?
	let boxSizing: String?
	let breakAfter: String?
	let breakBefore: String?
	let breakInside: String?
	let captionSide: String?
	let caretColor: String?
	let Charset: String?
	let clear: String?
	let clip: String?
	let clipPath: String?
	let color: String?
	let columnCount: String?
	let columnFill: String?
	let columnGap: String?
	let columnRule: String?
	let columnRuleColor: String?
	let columnRuleStyle: String?
	let columnRuleWidth: String?
	let columnSpan: String?
	let columnWidth: String?
	let columns: String?
	let content: String?
	let counterIncrement: String?
	let counterReset: String?
	let counterSet: String?
	let cursor: String?
	let direction: String?
	let display: String?
	let emptyCells: String?
	let filter: String?
	let flex: String?
	let flexBasis: String?
	let flexDirection: String?
	let flexFlow: String?
	let flexGrow: String?
	let flexShrink: String?
	let flexWrap: String?
	let float: String?
	let font: String?
	let fontFamily: String?
	let fontFeatureSettings: String?
	let fontKerning: String?
	let fontLanguageOverride: String?
	let fontSize: String?
	let fontSizeAdjust: String?
	let fontStretch: String?
	let fontStyle: String?
	let fontSynthesis: String?
	let fontVariant: String?
	let fontVariantAlternates: String?
	let fontVariantCaps: String?
	let fontVariantEastAsian: String?
	let fontVariantLigatures: String?
	let fontVariantNumeric: String?
	let fontVariantPosition: String?
	let fontWeight: String?
	let gap: String?
	let grid: String?
	let gridArea: String?
	let gridAutoColumns: String?
	let gridAutoFlow: String?
	let gridAutoRows: String?
	let gridColumn: String?
	let gridColumnEnd: String?
	let gridColumnGap: String?
	let gridColumnStart: String?
	let gridGap: String?
	let gridRow: String?
	let gridRowEnd: String?
	let gridRowGap: String?
	let gridRowStart: String?
	let gridTemplate: String?
	let gridTemplateAreas: String?
	let gridTemplateColumns: String?
	let gridTemplateRows: String?
	let hangingPunctuation: String?
	let height: String?
	let hyphens: String?
	let hypenateCharacter: String?
	let imageRendering: String?
	let inlineSize: String?
	let inset: String?
	let insetBlock: String?
	let insetBlockEnd: String?
	let insetBlockStart: String?
	let insetInline: String?
	let insetInlineEnd: String?
	let insetInlineStart: String?
	let isolation: String?
	let justifyContent: Alignment?
	let justifyItems: Alignment?
	let justifySelf: Alignment?
	let left: String?
	let letterSpacing: String?
	let lineBreak: String?
	let lineHeight: String?
	let listStyle: String?
	let listStyleImage: String?
	let listStylePosition: String?
	let listStyleType: String?
	let margin: String?
	let marginBlock: String?
	let marginBlockEnd: String?
	let marginBlockStart: String?
	let marginBottom: String?
	let marginInline: String?
	let marginInlineEnd: String?
	let marginInlineStart: String?
	let marginLeft: String?
	let marginRight: String?
	let marginTop: String?
	let mask: String?
	let maskClip: String?
	let maskComposite: String?
	let maskImage: String?
	let maskMode: String?
	let maskOrigin: String?
	let maskPosition: String?
	let maskRepeat: String?
	let maskSize: String?
	let maskType: String?
	let maxHeight: String?
	let maxWidth: String?
	let maxBlockSize: String?
	let maxInlineSize: String?
	let minBlockSize: String?
	let minInlineSize: String?
	let minHeight: String?
	let minWidth: String?
	let mixBlendMode: String?
	let objectFit: String?
	let objectPosition: String?
	let offset: String?
	let offsetAnchor: String?
	let offsetDistance: String?
	let offsetPath: String?
	let offsetRotate: String?
	let opacity: String?
	let order: String?
	let orphans: String?
	let outline: String?
	let outlineColor: String?
	let outlineOffset: String?
	let outlineStyle: String?
	let outlineWidth: String?
	let overflow: String?
	let overflowAnchor: String?
	let overflowWrap: String?
	let overflowX: String?
	let overflowY: String?
	let overscrollBehavior: String?
	let overscrollBehaviorBlock: String?
	let overscrollBehaviorInline: String?
	let overscrollBehaviorX: String?
	let overscrollBehaviorY: String?
	let padding: String?
	let paddingBlock: String?
	let paddingBlockEnd: String?
	let paddingBlockStart: String?
	let paddingBottom: String?
	let paddingInline: String?
	let paddingInlineEnd: String?
	let paddingInlineStart: String?
	let paddingLeft: String?
	let paddingRight: String?
	let paddingTop: String?
	let pageBreakAfter: String?
	let pageBreakBefore: String?
	let pageBreakInside: String?
	let paintOrder: String?
	let perspective: String?
	let perspectiveOrigin: String?
	let placeContent: String?
	let placeItems: String?
	let placeSelf: String?
	let pointerEvents: String?
	let position: String?
	let quotes: String?
	let resize: String?
	let right: String?
	let rotate: String?
	let rowGap: String?
	let scale: String?
	let scrollBehavior: String?
	let scrollMargin: String?
	let scrollMarginBlock: String?
	let scrollMarginBlockEnd: String?
	let scrollMarginBlockStart: String?
	let scrollMarginBottom: String?
	let scrollMarginInline: String?
	let scrollMarginInlineEnd: String?
	let scrollMarginInlineStart: String?
	let scrollMarginLeft: String?
	let scrollMarginRight: String?
	let scrollMarginTop: String?
	let scrollPadding: String?
	let scrollPaddingBlock: String?
	let scrollPaddingBlockEnd: String?
	let scrollPaddingBlockStart: String?
	let scrollPaddingBottom: String?
	let scrollPaddingInline: String?
	let scrollPaddingInlineEnd: String?
	let scrollPaddingInlineStart: String?
	let scrollPaddingLeft: String?
	let scrollPaddingRight: String?
	let scrollPaddingTop: String?
	let scrollSnapAlign: String?
	let scrollSnapStop: String?
	let scrollSnapType: String?
	let scrollbarColor: String?
	let tabSize: String?
	let tableLayout: String?
	let textAlign: String?
	let textAlignLast: String?
	let textCombineUpright: String?
	let textDecoration: String?
	let textDecorationColor: String?
	let textDecorationLine: String?
	let textDecorationStyle: String?
	let textDecorationThickness: String?
	let textEmphasis: String?
	let textEmphasisColor: String?
	let textEmphasisPosition: String?
	let textEmphasisStyle: String?
	let textIndent: String?
	let textJustify: String?
	let textOrientation: String?
	let textOverflow: String?
	let textShadow: String?
	let textTransform: String?
	let textUnderlineOffset: String?
	let textUnderlinePosition: String?
	let top: String?
	let transform: String?
	let transformOrigin: String?
	let transformStyle: String?
	let transition: String?
	let transitionDelay: String?
	let transitionDuration: String?
	let transitionProperty: String?
	let transitionTimingFunction: String?
	let translate: String?
	let unicodeBidi: String?
	let userSelect: String?
	let verticalAlign: String?
	let visibility: String?
	let whiteSpace: String?
	let widows: String?
	let width: String?
	let wordBreak: String?
	let wordSpacing: String?
	let wordWrap: String?
	let writingMode: String?
	let zIndex: String?
}
